### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by LawrenceHan** [darkfriend77/SabberStone-gRPC#6]
Hi @darkfriend77 and @rnilva  ,

This a wonderful project, since the Unity project is hidden, I was wondering if you guys could share how you have done the animation?
As far as I know, the SabberStoneCore only processes the action and leaves a power log. So how to make the animation execute correctly from that log.

**Comment by darkfriend77** [comment]
I made the repository public,

https://github.com/darkfriend77/SabberStoneUnityClient

Have fun :-)

**Comment by LawrenceHan** [comment]
Thank you @darkfriend77 , you're awesome!
